# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions:			[ footnotes ]

# Setup
name: 고어쿤™
permalink: /:title/
about: 가장 최강의 위키니트.
urls:
    - text: blog
      url: http://blog.gorekun.com
    - text: github
      url: https://github.com/gorekun
    - text: email
      url: mailto:gorekun.com@gmail.com

