name: 고어쿤
markdown: redcarpet
pygments: true
permalink: /:title/
about: 가장 최강의 위키니트.
urls:
    - text: blog
      url: http://blog.gorekun.com
    - text: github
      url: https://github.com/gorekun
    - text: email
      url: mailto:gorekun.com@gmail.com

